services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.backend

    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/sketchbuddy

    ports:
      - 3001:3001

    depends_on:
      - postgres

    command: >
      sh -c "cd ./packages/db &&
             npx prisma migrate dev &&
             cd ../../ &&
             pnpm run start:backend"
             
  websocket:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.websocket

    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/sketchbuddy

    ports:
      - 8080:8080

    depends_on:
      - postgres

  frontend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend

    ports:
      - 3000:3000

    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001
      - NEXT_PUBLIC_WS_URL=ws://websocket:8080

    depends_on:
      backend:
        condition: service_started
      

  