FROM node:25-alpine

WORKDIR /app
RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./turbo.json ./turbo.json
COPY ./apps/web/package.json ./apps/web/package.json

RUN pnpm install
RUN pnpm run db:generate

COPY ./apps/web ./apps/web

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm","run","start:frontend"]