FROM node:25-alpine

WORKDIR /app
RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./turbo.json ./turbo.json
COPY ./apps/ws-backend/package.json ./apps/ws-backend/package.json

RUN pnpm install
RUN pnpm run db:generate

COPY ./apps/ws-backend ./apps/ws-backend

RUN pnpm run build

EXPOSE 8080

CMD ["pnpm","run","start:websocket"]