FROM node:25-alpine

WORKDIR /app
RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./turbo.json ./turbo.json
COPY ./apps/http-backend/package.json ./apps/http-backend/package.json

RUN pnpm install
RUN pnpm run db:generate

COPY ./apps/http-backend ./apps/http-backend

RUN pnpm run build

EXPOSE 3001

CMD ["pnpm","run","start:backend"]






